version: "2"
run:
  tests: false
skip-dirs:
  - ^chain
  - ^chain/.*
  - ^exchange
  - ^injective_data
  - ^proto
  - client/keyring/testdata
skip-files:
  - '**/chain_test_support.go'
linters:
  fast: false
  enable:
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
  disable:
    - unused
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - deferInLoop
        - hugeParam
        - unnamedResult
      enabled-tags:
        - performance
        - diagnostic
        - style
        - opinionated
        - experimental
    revive:
      enable-all-rules: true
      rules:
        - name: var-naming
          arguments:
            - - ID
        - name: add-constant
          disabled: true
        - name: line-length-limit
          arguments:
            - 140
        - name: cognitive-complexity
          arguments:
            - 20
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: ALL_CAPS
    paths:
      - chain
      - exchange
      - injective_data
      - proto
      - client/keyring/testdata
      - client/chain/chain_test_support.go
issues:
  max-issues-per-linter: 0
