{
  "run": {
    "tests": false,
  },
  "linters": {
    "fast": false,
    "enable": [
      "errcheck",
      "errorlint",
      "gas",
      "gocritic",
      "gosimple",
      "govet",
      "ineffassign",
      "megacheck",
      "misspell",
      "nakedret",
      "prealloc",
      "revive",
      "staticcheck",
      "unconvert",
      "unparam",
    ],
    "disable": [
      "unused",
    ]
  },
  "linters-settings": {
    "revive": {
      "enableAllRules": true,
      "rules": [
        {
          "name": "var-naming",
          "arguments": [
            ["ID"]
          ]
        }
      ]
    },
    "gocritic": {
      "enabled-tags": [
        "diagnostic",
        "experimental",
        "opinionated",
        "performance",
        "style",
      ],
      "disabled-checks": [
        "hugeParam",
      ]
    }
  },
}
