package main

import (
	"encoding/base64"
	"fmt"
	cosmostxpb "github.com/cosmos/cosmos-sdk/types/tx"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
)

var parserMap = map[string]interface{}{
	"/cosmos.bank.v1beta1.MsgSend":      banktypes.MsgSend{},
	"/cosmos.bank.v1beta1.MsgMultiSend": banktypes.MsgMultiSend{},
}

func main() {
	//multisend := "Cr0BCroBCiEvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dNdWx0aVNlbmQSlAEKSAoqaW5qMTd2eXRkd3FjenF6NzJqNjVzYXVrcGxya3RkNGd5Zm1lNWFnZjZjEhoKA2luahITMTAwMDAwMDAwMDAwMDAwMDAwMBJICippbmoxN3Z5dGR3cWN6cXo3Mmo2NXNhdWtwbHJrdGQ0Z3lmbWU1YWdmNmMSGgoDaW5qEhMxMDAwMDAwMDAwMDAwMDAwMDAwEn8KYApUCi0vaW5qZWN0aXZlLmNyeXB0by52MWJldGExLmV0aHNlY3AyNTZrMS5QdWJLZXkSIwohA5Bh/pUwQH5Sgsniw2eFD5lZHswzGUxzuaaH8g0xKzO2EgQKAggBGPm7CBIbChUKA2luahIONjAzMDQ1MDAwMDAwMDAQoa4HGkFuew+TP4HtsHcXFtFcg33d5QeJZCLmT3glrpgbY+NKbCQ9IGiIzMke1kql9DTEdKFqyMPXvfUQ4bUTXq2tCV7HAA=="
	send := "CpsLCpgLCjAvaW5qZWN0aXZlLmV4Y2hhbmdlLnYxYmV0YTEuTXNnQmF0Y2hVcGRhdGVPcmRlcnMS4woKKmluajF4d3ZjcXpxdW10bmUzand1anIwZjk3ajgzc2F0cDB6MmV4NHBlZSrMAQpCMHg3ZjcxYzRmYmEzNzVjOTY0YmU4ZGI3ZmM3YTUyNzVkOTc0ZjhjNmNkYzRkNzU4ZjJhYzQ5OTdmMTA2YmIwNTJiEkIweDMzOTk4MDA4MWNkYWU3OThjOWRjOTBkZTkyZmE0NzhjM2FiMGJjNGEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAaQjB4OTU2MzMxMDU3Y2U5Zjg1MTI2NWExOTFjNWY4OGYwOTcxODFiZGJkZWYwZTE4ZjI5NGY0N2E5NzdjZDRiYmY3ZCrMAQpCMHg3ZjcxYzRmYmEzNzVjOTY0YmU4ZGI3ZmM3YTUyNzVkOTc0ZjhjNmNkYzRkNzU4ZjJhYzQ5OTdmMTA2YmIwNTJiEkIweDMzOTk4MDA4MWNkYWU3OThjOWRjOTBkZTkyZmE0NzhjM2FiMGJjNGEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAaQjB4NGYzNDk5ZmY0MTRmOTUwYmZlMWUyYWNkODFhYzlkMGQ0YzAzMDA4ZTU3NzZiMDVlYWJjZGRhZDk4YWViMTIxYyrMAQpCMHg3ZjcxYzRmYmEzNzVjOTY0YmU4ZGI3ZmM3YTUyNzVkOTc0ZjhjNmNkYzRkNzU4ZjJhYzQ5OTdmMTA2YmIwNTJiEkIweDMzOTk4MDA4MWNkYWU3OThjOWRjOTBkZTkyZmE0NzhjM2FiMGJjNGEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAaQjB4MjhmOWQ0ODc4ZTRiZjA3YjczMTg3NDdmZWM3OTYxYzY3YmViNTMwZjAyYmE3ZmU5ZDA0OWRmMWI0NjUxNzA4OTrrAQpCMHg3ZjcxYzRmYmEzNzVjOTY0YmU4ZGI3ZmM3YTUyNzVkOTc0ZjhjNmNkYzRkNzU4ZjJhYzQ5OTdmMTA2YmIwNTJiEqIBCkIweDMzOTk4MDA4MWNkYWU3OThjOWRjOTBkZTkyZmE0NzhjM2FiMGJjNGEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDASKmluajF4d3ZjcXpxdW10bmUzand1anIwZjk3ajgzc2F0cDB6MmV4NHBlZRoGMTg5MDAwIig0MjY4MDQ0MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwGAc66wEKQjB4N2Y3MWM0ZmJhMzc1Yzk2NGJlOGRiN2ZjN2E1Mjc1ZDk3NGY4YzZjZGM0ZDc1OGYyYWM0OTk3ZjEwNmJiMDUyYhKiAQpCMHgzMzk5ODAwODFjZGFlNzk4YzlkYzkwZGU5MmZhNDc4YzNhYjBiYzRhMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwEippbmoxeHd2Y3F6cXVtdG5lM2p3dWpyMGY5N2o4M3NhdHAwejJleDRwZWUaBjIxNTAwMCIoMzkzMzMyODAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMBgHOusBCkIweDdmNzFjNGZiYTM3NWM5NjRiZThkYjdmYzdhNTI3NWQ5NzRmOGM2Y2RjNGQ3NThmMmFjNDk5N2YxMDZiYjA1MmISogEKQjB4MzM5OTgwMDgxY2RhZTc5OGM5ZGM5MGRlOTJmYTQ3OGMzYWIwYmM0YTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMBIqaW5qMXh3dmNxenF1bXRuZTNqd3VqcjBmOTdqODNzYXRwMHoyZXg0cGVlGgYyNTAwMDAiKDIwNTk4NjMwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAYCBKAAQpgClQKLS9pbmplY3RpdmUuY3J5cHRvLnYxYmV0YTEuZXRoc2VjcDI1NmsxLlB1YktleRIjCiEDobYao8nZtbLPtYNhZrzVnMFVL3u5FxBHSMTbVQkuy9oSBAoCCAEY//06EhwKFgoDaW5qEg8xNzY1MzY1MDAwMDAwMDAQscYVGkGYUmgF5FFW6Qsj6Dv1HP3kUSTj48R+YC4ZEDr12lJcki2Ya22pwFJR/LDZcXrqw1L9tE4ps+zOnQNf7daDI+VRAA=="
	bytes, _ := base64.StdEncoding.DecodeString(send)
	rawTx := cosmostxpb.TxRaw{}
	rawTx.Unmarshal(bytes)

	txBody := cosmostxpb.TxBody{}
	txBody.Unmarshal(rawTx.BodyBytes)

	for _, msg := range txBody.Messages {
		switch parserMap[msg.TypeUrl].(type) {
		case banktypes.MsgSend:
			var result banktypes.MsgSend
			result.XXX_Unmarshal(msg.Value)
			fmt.Println(result.FromAddress)
			fmt.Println(result.ToAddress)
			fmt.Println(result.Amount)

		case banktypes.MsgMultiSend:
			var result banktypes.MsgMultiSend
			result.XXX_Unmarshal(msg.Value)
			inputs := result.Inputs
			outputs := result.Outputs

			fmt.Println(inputs)
			fmt.Println(outputs)

		default:
			fmt.Println("Unexpected Type:", msg.TypeUrl)
		}
	}
}
