// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: injective/oracle/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRelayPriceFeedPrice defines a SDK message for setting a price through the pricefeed oracle.
type MsgRelayPriceFeedPrice struct {
	Sender string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Base   []string `protobuf:"bytes,2,rep,name=base,proto3" json:"base,omitempty"`
	Quote  []string `protobuf:"bytes,3,rep,name=quote,proto3" json:"quote,omitempty"`
	// price defines the price of the oracle base and quote
	Price []github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,rep,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price"`
}

func (m *MsgRelayPriceFeedPrice) Reset()         { *m = MsgRelayPriceFeedPrice{} }
func (m *MsgRelayPriceFeedPrice) String() string { return proto.CompactTextString(m) }
func (*MsgRelayPriceFeedPrice) ProtoMessage()    {}
func (*MsgRelayPriceFeedPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdf1c490eba4310, []int{0}
}
func (m *MsgRelayPriceFeedPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRelayPriceFeedPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRelayPriceFeedPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRelayPriceFeedPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRelayPriceFeedPrice.Merge(m, src)
}
func (m *MsgRelayPriceFeedPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgRelayPriceFeedPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRelayPriceFeedPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRelayPriceFeedPrice proto.InternalMessageInfo

type MsgRelayPriceFeedPriceResponse struct {
}

func (m *MsgRelayPriceFeedPriceResponse) Reset()         { *m = MsgRelayPriceFeedPriceResponse{} }
func (m *MsgRelayPriceFeedPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRelayPriceFeedPriceResponse) ProtoMessage()    {}
func (*MsgRelayPriceFeedPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdf1c490eba4310, []int{1}
}
func (m *MsgRelayPriceFeedPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRelayPriceFeedPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRelayPriceFeedPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRelayPriceFeedPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRelayPriceFeedPriceResponse.Merge(m, src)
}
func (m *MsgRelayPriceFeedPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRelayPriceFeedPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRelayPriceFeedPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRelayPriceFeedPriceResponse proto.InternalMessageInfo

type MsgRelayBandRates struct {
	Relayer      string   `protobuf:"bytes,1,opt,name=relayer,proto3" json:"relayer,omitempty"`
	Symbols      []string `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Rates        []uint64 `protobuf:"varint,3,rep,packed,name=rates,proto3" json:"rates,omitempty"`
	ResolveTimes []uint64 `protobuf:"varint,4,rep,packed,name=resolve_times,json=resolveTimes,proto3" json:"resolve_times,omitempty"`
	RequestIDs   []uint64 `protobuf:"varint,5,rep,packed,name=requestIDs,proto3" json:"requestIDs,omitempty"`
}

func (m *MsgRelayBandRates) Reset()         { *m = MsgRelayBandRates{} }
func (m *MsgRelayBandRates) String() string { return proto.CompactTextString(m) }
func (*MsgRelayBandRates) ProtoMessage()    {}
func (*MsgRelayBandRates) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdf1c490eba4310, []int{2}
}
func (m *MsgRelayBandRates) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRelayBandRates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRelayBandRates.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRelayBandRates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRelayBandRates.Merge(m, src)
}
func (m *MsgRelayBandRates) XXX_Size() int {
	return m.Size()
}
func (m *MsgRelayBandRates) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRelayBandRates.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRelayBandRates proto.InternalMessageInfo

func (m *MsgRelayBandRates) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func (m *MsgRelayBandRates) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

func (m *MsgRelayBandRates) GetRates() []uint64 {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *MsgRelayBandRates) GetResolveTimes() []uint64 {
	if m != nil {
		return m.ResolveTimes
	}
	return nil
}

func (m *MsgRelayBandRates) GetRequestIDs() []uint64 {
	if m != nil {
		return m.RequestIDs
	}
	return nil
}

type MsgRelayBandRatesResponse struct {
}

func (m *MsgRelayBandRatesResponse) Reset()         { *m = MsgRelayBandRatesResponse{} }
func (m *MsgRelayBandRatesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRelayBandRatesResponse) ProtoMessage()    {}
func (*MsgRelayBandRatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdf1c490eba4310, []int{3}
}
func (m *MsgRelayBandRatesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRelayBandRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRelayBandRatesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRelayBandRatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRelayBandRatesResponse.Merge(m, src)
}
func (m *MsgRelayBandRatesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRelayBandRatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRelayBandRatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRelayBandRatesResponse proto.InternalMessageInfo

// MsgRelayCoinbaseMessages defines a SDK message for relaying price messages from Coinbase API.
type MsgRelayCoinbaseMessages struct {
	Sender     string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Messages   [][]byte `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Signatures [][]byte `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *MsgRelayCoinbaseMessages) Reset()         { *m = MsgRelayCoinbaseMessages{} }
func (m *MsgRelayCoinbaseMessages) String() string { return proto.CompactTextString(m) }
func (*MsgRelayCoinbaseMessages) ProtoMessage()    {}
func (*MsgRelayCoinbaseMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdf1c490eba4310, []int{4}
}
func (m *MsgRelayCoinbaseMessages) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRelayCoinbaseMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRelayCoinbaseMessages.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRelayCoinbaseMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRelayCoinbaseMessages.Merge(m, src)
}
func (m *MsgRelayCoinbaseMessages) XXX_Size() int {
	return m.Size()
}
func (m *MsgRelayCoinbaseMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRelayCoinbaseMessages.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRelayCoinbaseMessages proto.InternalMessageInfo

type MsgRelayCoinbaseMessagesResponse struct {
}

func (m *MsgRelayCoinbaseMessagesResponse) Reset()         { *m = MsgRelayCoinbaseMessagesResponse{} }
func (m *MsgRelayCoinbaseMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRelayCoinbaseMessagesResponse) ProtoMessage()    {}
func (*MsgRelayCoinbaseMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fdf1c490eba4310, []int{5}
}
func (m *MsgRelayCoinbaseMessagesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRelayCoinbaseMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRelayCoinbaseMessagesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRelayCoinbaseMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRelayCoinbaseMessagesResponse.Merge(m, src)
}
func (m *MsgRelayCoinbaseMessagesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRelayCoinbaseMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRelayCoinbaseMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRelayCoinbaseMessagesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRelayPriceFeedPrice)(nil), "injective.oracle.v1beta1.MsgRelayPriceFeedPrice")
	proto.RegisterType((*MsgRelayPriceFeedPriceResponse)(nil), "injective.oracle.v1beta1.MsgRelayPriceFeedPriceResponse")
	proto.RegisterType((*MsgRelayBandRates)(nil), "injective.oracle.v1beta1.MsgRelayBandRates")
	proto.RegisterType((*MsgRelayBandRatesResponse)(nil), "injective.oracle.v1beta1.MsgRelayBandRatesResponse")
	proto.RegisterType((*MsgRelayCoinbaseMessages)(nil), "injective.oracle.v1beta1.MsgRelayCoinbaseMessages")
	proto.RegisterType((*MsgRelayCoinbaseMessagesResponse)(nil), "injective.oracle.v1beta1.MsgRelayCoinbaseMessagesResponse")
}

func init() { proto.RegisterFile("injective/oracle/v1beta1/tx.proto", fileDescriptor_5fdf1c490eba4310) }

var fileDescriptor_5fdf1c490eba4310 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6b, 0x13, 0x41,
	0x18, 0xde, 0x35, 0x49, 0x6d, 0x87, 0x28, 0x38, 0xd6, 0xb2, 0xae, 0xb0, 0x89, 0x11, 0xa5, 0x20,
	0xdd, 0xb5, 0xed, 0x45, 0x7a, 0x8c, 0x41, 0x28, 0x34, 0x20, 0x8b, 0x27, 0x2f, 0x32, 0xbb, 0x79,
	0xdd, 0xae, 0x66, 0x77, 0xd2, 0x79, 0x27, 0xa1, 0x39, 0x7a, 0xaa, 0x47, 0x7f, 0x42, 0xf1, 0xe8,
	0x2f, 0xe9, 0xb1, 0x47, 0xf1, 0x50, 0x24, 0xb9, 0xf8, 0x33, 0x64, 0x66, 0x3f, 0x5c, 0xda, 0x84,
	0x92, 0xd3, 0xce, 0xf3, 0xcc, 0xf3, 0x7e, 0x3c, 0xfb, 0xce, 0x0c, 0x79, 0x1a, 0xa7, 0x9f, 0x21,
	0x94, 0xf1, 0x04, 0x3c, 0x2e, 0x58, 0x38, 0x04, 0x6f, 0xb2, 0x1b, 0x80, 0x64, 0xbb, 0x9e, 0x3c,
	0x75, 0x47, 0x82, 0x4b, 0x4e, 0xad, 0x52, 0xe2, 0x66, 0x12, 0x37, 0x97, 0xd8, 0x9b, 0x11, 0x8f,
	0xb8, 0x16, 0x79, 0x6a, 0x95, 0xe9, 0x6d, 0x27, 0xe4, 0x98, 0x70, 0xf4, 0x02, 0x86, 0xff, 0xb3,
	0x85, 0x3c, 0x4e, 0xf3, 0xfd, 0xe7, 0x4b, 0x4b, 0xe6, 0xe9, 0xb5, 0xac, 0xf3, 0xd3, 0x24, 0x5b,
	0x7d, 0x8c, 0x7c, 0x18, 0xb2, 0xe9, 0x3b, 0x11, 0x87, 0xf0, 0x16, 0x60, 0xa0, 0x17, 0x74, 0x8b,
	0xac, 0x21, 0xa4, 0x03, 0x10, 0x96, 0xd9, 0x36, 0xb7, 0x37, 0xfc, 0x1c, 0x51, 0x4a, 0xea, 0xaa,
	0xa8, 0x75, 0xa7, 0x5d, 0xdb, 0xde, 0xf0, 0xf5, 0x9a, 0x6e, 0x92, 0xc6, 0xc9, 0x98, 0x4b, 0xb0,
	0x6a, 0x9a, 0xcc, 0x00, 0xed, 0x91, 0xc6, 0x48, 0xa5, 0xb2, 0xea, 0x8a, 0xed, 0xba, 0x17, 0x57,
	0x2d, 0xe3, 0xf7, 0x55, 0xeb, 0x45, 0x14, 0xcb, 0xe3, 0x71, 0xe0, 0x86, 0x3c, 0xf1, 0x72, 0x17,
	0xd9, 0x67, 0x07, 0x07, 0x5f, 0x3c, 0x39, 0x1d, 0x01, 0xba, 0x3d, 0x08, 0xfd, 0x2c, 0xf8, 0x60,
	0xfd, 0xdb, 0x79, 0xcb, 0xf8, 0x7b, 0xde, 0x32, 0x3a, 0x6d, 0xe2, 0x2c, 0xee, 0xd5, 0x07, 0x1c,
	0xf1, 0x14, 0xa1, 0xf3, 0xc3, 0x24, 0x0f, 0x0a, 0x49, 0x97, 0xa5, 0x03, 0x9f, 0x49, 0x40, 0x6a,
	0x91, 0xbb, 0x42, 0x31, 0xa5, 0x95, 0x02, 0xaa, 0x1d, 0x9c, 0x26, 0x01, 0x1f, 0x62, 0x6e, 0xa7,
	0x80, 0xca, 0x91, 0x50, 0xc1, 0xda, 0x51, 0xdd, 0xcf, 0x00, 0x7d, 0x46, 0xee, 0x09, 0x40, 0x3e,
	0x9c, 0xc0, 0x47, 0x19, 0x27, 0x80, 0xda, 0x59, 0xdd, 0x6f, 0xe6, 0xe4, 0x7b, 0xc5, 0x51, 0x87,
	0x10, 0x01, 0x27, 0x63, 0x40, 0x79, 0xd8, 0x43, 0xab, 0xa1, 0x15, 0x15, 0xa6, 0xf3, 0x84, 0x3c,
	0xbe, 0xd1, 0x63, 0xe9, 0xe0, 0x94, 0x58, 0xc5, 0xe6, 0x1b, 0x1e, 0xa7, 0xea, 0xef, 0xf6, 0x01,
	0x91, 0x45, 0x80, 0x4b, 0x27, 0x62, 0x93, 0xf5, 0x24, 0xd7, 0x68, 0x1b, 0x4d, 0xbf, 0xc4, 0xaa,
	0x19, 0x8c, 0xa3, 0x94, 0xc9, 0xb1, 0xc8, 0xcd, 0x34, 0xfd, 0x0a, 0x53, 0xf9, 0xbb, 0x1d, 0xd2,
	0x5e, 0x56, 0xb9, 0xe8, 0x6e, 0xef, 0xac, 0x46, 0x6a, 0x7d, 0x8c, 0xe8, 0x57, 0x93, 0x3c, 0x5c,
	0x74, 0x66, 0x5e, 0xb9, 0xcb, 0x8e, 0xb1, 0xbb, 0x78, 0x72, 0xf6, 0xeb, 0x55, 0x23, 0x8a, 0x5e,
	0xa8, 0x20, 0xf7, 0xaf, 0xcd, 0xf9, 0xe5, 0xed, 0xb9, 0x4a, 0xb1, 0xbd, 0xbf, 0x82, 0xb8, 0xac,
	0x79, 0x66, 0x92, 0x47, 0x8b, 0x67, 0xb3, 0x77, 0x7b, 0xba, 0xeb, 0x31, 0xf6, 0xc1, 0xea, 0x31,
	0x45, 0x27, 0xdd, 0x4f, 0x17, 0x33, 0xc7, 0xbc, 0x9c, 0x39, 0xe6, 0x9f, 0x99, 0x63, 0x7e, 0x9f,
	0x3b, 0xc6, 0xe5, 0xdc, 0x31, 0x7e, 0xcd, 0x1d, 0xe3, 0xc3, 0x51, 0xe5, 0x7a, 0x1d, 0x16, 0xf9,
	0x8f, 0x58, 0x80, 0x5e, 0x59, 0x6d, 0x27, 0xe4, 0x02, 0xaa, 0xf0, 0x98, 0xc5, 0xa9, 0x97, 0xf0,
	0xc1, 0x78, 0x08, 0x58, 0xbc, 0x17, 0xfa, 0x22, 0x06, 0x6b, 0xfa, 0x9d, 0xd8, 0xff, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0xa3, 0x51, 0x54, 0xc3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RelayPriceFeedPrice defines a method for relaying a price for a price feeder-based oracle
	RelayPriceFeedPrice(ctx context.Context, in *MsgRelayPriceFeedPrice, opts ...grpc.CallOption) (*MsgRelayPriceFeedPriceResponse, error)
	// RelayBandRates defines a method for relaying rates from Band
	RelayBandRates(ctx context.Context, in *MsgRelayBandRates, opts ...grpc.CallOption) (*MsgRelayBandRatesResponse, error)
	// RelayCoinbaseMessages defines a method for relaying price messages from Coinbase API
	RelayCoinbaseMessages(ctx context.Context, in *MsgRelayCoinbaseMessages, opts ...grpc.CallOption) (*MsgRelayCoinbaseMessagesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RelayPriceFeedPrice(ctx context.Context, in *MsgRelayPriceFeedPrice, opts ...grpc.CallOption) (*MsgRelayPriceFeedPriceResponse, error) {
	out := new(MsgRelayPriceFeedPriceResponse)
	err := c.cc.Invoke(ctx, "/injective.oracle.v1beta1.Msg/RelayPriceFeedPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RelayBandRates(ctx context.Context, in *MsgRelayBandRates, opts ...grpc.CallOption) (*MsgRelayBandRatesResponse, error) {
	out := new(MsgRelayBandRatesResponse)
	err := c.cc.Invoke(ctx, "/injective.oracle.v1beta1.Msg/RelayBandRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RelayCoinbaseMessages(ctx context.Context, in *MsgRelayCoinbaseMessages, opts ...grpc.CallOption) (*MsgRelayCoinbaseMessagesResponse, error) {
	out := new(MsgRelayCoinbaseMessagesResponse)
	err := c.cc.Invoke(ctx, "/injective.oracle.v1beta1.Msg/RelayCoinbaseMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RelayPriceFeedPrice defines a method for relaying a price for a price feeder-based oracle
	RelayPriceFeedPrice(context.Context, *MsgRelayPriceFeedPrice) (*MsgRelayPriceFeedPriceResponse, error)
	// RelayBandRates defines a method for relaying rates from Band
	RelayBandRates(context.Context, *MsgRelayBandRates) (*MsgRelayBandRatesResponse, error)
	// RelayCoinbaseMessages defines a method for relaying price messages from Coinbase API
	RelayCoinbaseMessages(context.Context, *MsgRelayCoinbaseMessages) (*MsgRelayCoinbaseMessagesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RelayPriceFeedPrice(ctx context.Context, req *MsgRelayPriceFeedPrice) (*MsgRelayPriceFeedPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelayPriceFeedPrice not implemented")
}
func (*UnimplementedMsgServer) RelayBandRates(ctx context.Context, req *MsgRelayBandRates) (*MsgRelayBandRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelayBandRates not implemented")
}
func (*UnimplementedMsgServer) RelayCoinbaseMessages(ctx context.Context, req *MsgRelayCoinbaseMessages) (*MsgRelayCoinbaseMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelayCoinbaseMessages not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RelayPriceFeedPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRelayPriceFeedPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RelayPriceFeedPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective.oracle.v1beta1.Msg/RelayPriceFeedPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RelayPriceFeedPrice(ctx, req.(*MsgRelayPriceFeedPrice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RelayBandRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRelayBandRates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RelayBandRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective.oracle.v1beta1.Msg/RelayBandRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RelayBandRates(ctx, req.(*MsgRelayBandRates))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RelayCoinbaseMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRelayCoinbaseMessages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RelayCoinbaseMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/injective.oracle.v1beta1.Msg/RelayCoinbaseMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RelayCoinbaseMessages(ctx, req.(*MsgRelayCoinbaseMessages))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "injective.oracle.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayPriceFeedPrice",
			Handler:    _Msg_RelayPriceFeedPrice_Handler,
		},
		{
			MethodName: "RelayBandRates",
			Handler:    _Msg_RelayBandRates_Handler,
		},
		{
			MethodName: "RelayCoinbaseMessages",
			Handler:    _Msg_RelayCoinbaseMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "injective/oracle/v1beta1/tx.proto",
}

func (m *MsgRelayPriceFeedPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelayPriceFeedPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRelayPriceFeedPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Price) > 0 {
		for iNdEx := len(m.Price) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Price[iNdEx].Size()
				i -= size
				if _, err := m.Price[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Quote) > 0 {
		for iNdEx := len(m.Quote) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Quote[iNdEx])
			copy(dAtA[i:], m.Quote[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Quote[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Base) > 0 {
		for iNdEx := len(m.Base) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Base[iNdEx])
			copy(dAtA[i:], m.Base[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Base[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRelayPriceFeedPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelayPriceFeedPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRelayPriceFeedPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRelayBandRates) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelayBandRates) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRelayBandRates) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestIDs) > 0 {
		dAtA2 := make([]byte, len(m.RequestIDs)*10)
		var j1 int
		for _, num := range m.RequestIDs {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTx(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ResolveTimes) > 0 {
		dAtA4 := make([]byte, len(m.ResolveTimes)*10)
		var j3 int
		for _, num := range m.ResolveTimes {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintTx(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Rates) > 0 {
		dAtA6 := make([]byte, len(m.Rates)*10)
		var j5 int
		for _, num := range m.Rates {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintTx(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Symbols) > 0 {
		for iNdEx := len(m.Symbols) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Symbols[iNdEx])
			copy(dAtA[i:], m.Symbols[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Symbols[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRelayBandRatesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelayBandRatesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRelayBandRatesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRelayCoinbaseMessages) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelayCoinbaseMessages) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRelayCoinbaseMessages) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signatures[iNdEx])
			copy(dAtA[i:], m.Signatures[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Signatures[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Messages) > 0 {
		for iNdEx := len(m.Messages) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Messages[iNdEx])
			copy(dAtA[i:], m.Messages[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Messages[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRelayCoinbaseMessagesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRelayCoinbaseMessagesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRelayCoinbaseMessagesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRelayPriceFeedPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Base) > 0 {
		for _, s := range m.Base {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Quote) > 0 {
		for _, s := range m.Quote {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Price) > 0 {
		for _, e := range m.Price {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRelayPriceFeedPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRelayBandRates) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Symbols) > 0 {
		for _, s := range m.Symbols {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Rates) > 0 {
		l = 0
		for _, e := range m.Rates {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	if len(m.ResolveTimes) > 0 {
		l = 0
		for _, e := range m.ResolveTimes {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	if len(m.RequestIDs) > 0 {
		l = 0
		for _, e := range m.RequestIDs {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgRelayBandRatesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRelayCoinbaseMessages) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Messages) > 0 {
		for _, b := range m.Messages {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Signatures) > 0 {
		for _, b := range m.Signatures {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRelayCoinbaseMessagesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRelayPriceFeedPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelayPriceFeedPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelayPriceFeedPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Base = append(m.Base, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quote", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quote = append(m.Quote, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.Price = append(m.Price, v)
			if err := m.Price[len(m.Price)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRelayPriceFeedPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelayPriceFeedPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelayPriceFeedPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRelayBandRates) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelayBandRates: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelayBandRates: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbols", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbols = append(m.Symbols, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Rates = append(m.Rates, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Rates) == 0 {
					m.Rates = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Rates = append(m.Rates, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Rates", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ResolveTimes = append(m.ResolveTimes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ResolveTimes) == 0 {
					m.ResolveTimes = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ResolveTimes = append(m.ResolveTimes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolveTimes", wireType)
			}
		case 5:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RequestIDs = append(m.RequestIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RequestIDs) == 0 {
					m.RequestIDs = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RequestIDs = append(m.RequestIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestIDs", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRelayBandRatesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelayBandRatesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelayBandRatesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRelayCoinbaseMessages) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelayCoinbaseMessages: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelayCoinbaseMessages: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, make([]byte, postIndex-iNdEx))
			copy(m.Messages[len(m.Messages)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, make([]byte, postIndex-iNdEx))
			copy(m.Signatures[len(m.Signatures)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRelayCoinbaseMessagesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRelayCoinbaseMessagesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRelayCoinbaseMessagesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
