name: run-tests
on:
  pull_request:
  push:
    branches: [ master, dev ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Run test and calculate coverage
        run: make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
